sudo: false

language: go

go:
  - 1.6.x
  - 1.7.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps
  - make deps-test
  - go get -v github.com/mattn/goveralls

script:
  - go test -covermode count -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out
