language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - make deps
  - make deps-test
  - go get -v github.com/mattn/goveralls
  - npm install -g codeclimate-test-reporter

script:
  - go test -covermode count -coverprofile cover.out
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out
  - codeclimate-test-reporter < cover.out
